wiki/encyclopedia/urls.py
from django.urls import path

from . import views,util

app_name="main"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>",views.goto,name="page"),
    path("search",views.search,name="search"),
    path("NewPage",views.new_page,name="new_page"),
    path("create_entry",views.create,name="create"),
    path("redirect/<str:title>",views.redirect,name="redirect"),
    path("edit",views.edit,name="edit"),
    path("random_page",views.random_page,name="random_page")

]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import markdown2
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect,HttpResponse
from . import util
from random import randint


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
def goto(request,entry):
    page=util.get_entry(entry)
    if(page):
        return render(request,"encyclopedia/entry.html",{
        "content":markdown2.markdown(page),"title":entry
        })
    return render(request,"encyclopedia/error.html",{
        "error_msg":"Page doesnt exist"
    })
def search(request):
    query=request.POST.get("q")
    if(util.get_entry(query)): #if the page is in our enteries
        return HttpResponseRedirect(reverse("main:page",args=[query]))
    else:
        query_list=util.list_entries()
        result=[]
        for q in query_list:
            sub=str(query).lower()
            item=str(q).lower()
            if item.find(sub)!=-1:
                result.append(q)

    return render(request,"encyclopedia/search.html",{
        "result_list":result
        })     
def new_page(request):
    return render(request,"encyclopedia/newpage.html")

def create(request):
    title=request.POST.get("title")
    body=request.POST.get("body")
    if(util.get_entry(title)):
        return render(request,"encyclopedia/error.html",{
            "error_msg":"Page already exists"
        })
    else:
        title=title.capitalize()
        content="# "+title+"\n" +body
        util.save_entry(title,content)
        return HttpResponseRedirect(reverse("main:page",args=[title]))

def redirect(request,title):
    body=util.get_entry(title)  
    return render(request,"encyclopedia/edit.html",{
        "title":title,"body":body
    })
def edit(request):
    title=request.POST.get("title")
    content=request.POST.get("body")
    util.save_entry(title,content)
    return HttpResponseRedirect(reverse("main:page",args=[title]))
def random_page(request):
    entries=util.list_entries()
    num=randint(0,len(entries)-1) 
    title=entries[num]
    return HttpResponseRedirect(reverse("main:page",args=[title]))

    

    
    

wiki/encyclopedia/templates/encyclopedia/edit.html
{%extends "encyclopedia/layout.html"%}

{%block title%}
Edit page
{%endblock%}

{%block body%}
<h1>Edit page</h1><br>
    <form action="{%url 'main:edit'%}" method="POST">
        {% csrf_token %}
     <div class="form-group">
        <label for="title" id="title_label">Title:</label><br>
        <input type="text" id="title" name="title" value="{{title}}" readonly>
     </div>
      <div class="form-group">
         <label for="body" id="body_label">Body:</label>
         <textarea class="form-control" name="body" id="body" rows="20">{{body}}</textarea>
        </div>
        <input class="butn btn-primary" type="submit" value="Submit" id="submit_btn">
    </form>
{%endblock%}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{%block title%}
    {{title}}
{%endblock%}

{%block body%}
    {{content|safe}}
<form action="{%url 'main:redirect' title%}"method="GET">
        {% csrf_token %}
        <input class="btn btn-primary" type="submit"value="Edit" name="edit_btn" id="edit_btn">
    </form>
{%endblock%}

wiki/encyclopedia/templates/encyclopedia/error.html
{%extends "encyclopedia/layout.html" %}

{%block title%}
    Error
{%endblock%}

{%block body%}

<h1>{{error_msg}}</h1>
{%endblock%}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>


    <ul>
        {% for entry in entries %}
            <li>
            <a href="{% url 'main:page' entry %}">{{entry}}</a>
            
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
          <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{%url 'main:search' %}" method="POST">
                    {% csrf_token %}
                    {{form}}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'main:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'main:new_page'%}">Create New Page</a>
                </div>
                <div>
                    <a href="{%url 'main:random_page'%}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html"%}

{%block title%}
    New Page
{% endblock %}

{%block body%}
    <h1>Create a new page</h1><br>
    <form action="{%url 'main:create'%}" method="POST">
        {% csrf_token %}
     <div class="form-group">
        <label for="title" id="title_label">Title:</label><br>
        <input type="text" id="title" name="title">
     </div>
      <div class="form-group">
         <label for="body" id="body_label">Body:</label>
         <textarea class="form-control" name="body" id="body" rows="20"></textarea>
        </div>
        <input class="butn btn-primary" type="submit" value="Submit" id="submit_btn">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{%extends "encyclopedia/layout.html"%}

{%block title%}
    Search result
{%endblock%}

{%block body%}
    <h1>Search Results:</h1>
    <ul>
        {%for result in result_list%}
            <li>
               <a href="{% url 'main:page' result %}">{{result}}</a> 
            </li>
        {% endfor %}
    </ul>
{% endblock %}